version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@3.1.0
parameters:
  update-sheet-11:
    type: boolean
    default: false

jobs:
  build-and-deploy:
    parameters:
      sheet:
        type: string
        default: ""
    docker:
      - image: cimg/node:18.13.0
    steps:
      - run:
          name: set environment
          command: |
            case $CIRCLE_BRANCH in
              master)
                echo "export CDN_SHEETS_FOLDER=custom-sheets-production" >> $BASH_ENV
                echo "export VITE_CDN_SHEETS_FOLDER=custom-sheets-production" >> $BASH_ENV
                ;;
              staging)
                echo "export CDN_SHEETS_FOLDER=custom-sheets-staging" >> $BASH_ENV
                echo "export VITE_CDN_SHEETS_FOLDER=custom-sheets-staging" >> $BASH_ENV
                ;;
              feature/CSC-1652-gh-action-for-processing-custom-sheets)
                echo "export CDN_SHEETS_FOLDER=custom-sheets-staging" >> $BASH_ENV
                echo "export VITE_CDN_SHEETS_FOLDER=custom-sheets-staging" >> $BASH_ENV
                ;;
              *)
                exit 1
                ;;
            esac
      - checkout:
          path: ~/custom-sheets
      - gcp-cli/install
      - gcp-cli/setup:
          gcloud_service_key: GCLOUD_SERVICE_KEY_DECODED
          google_project_id: GCLOUD_PROJECT_ID
      - run:
          name: install packages
          command: npm install -g bun
      - run:
          working_directory: "~/custom-sheets/contrib/sheet-pixie"
          name: install packages
          command: bun install
      - run:
          working_directory: "~/custom-sheets/contrib/sheet-pixie"
          name: build sheet
          command: "bun run index.ts '../../<< parameters.sheet >>/sheet.json'"
      - run:
          working_directory: "~/custom-sheets/<< parameters.sheet >>"
          name: run ci deploy script
          command: bash release-ci.sh
workflows:
  update-sheet-11:
    when: << pipeline.parameters.update-sheet-11
    jobs:
      - build-and-deploy:
          sheet: "5eShaped"
          context:
            - roll20-private-sheets
            - npm-private-package-auth
          filters: &customsheetfilters
            branches:
              only:
                - feature/CSC-1652-gh-action-for-processing-custom-sheets
                - staging
